name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Golang Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Test
        run: go test -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Golang Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      - name: Calc coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out

      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
